application: coverfm
version: 2
runtime: python
api_version: 1

handlers:
- url: /update
  script: coverfm.py
  login: admin

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /.*
  script: coverfm.py
