application: coverfm
version: 8
runtime: python
api_version: 1

builtins:
- remote_api: on

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /ad/.*
  login: admin
  script: coverfm.py

- url: /.*
  script: coverfm.py
