application: coverfm-hrd
version: 10
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: PIL
  version: "1.1.7"

builtins:
- remote_api: on

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /ad/.*
  login: admin
  script: coverfm.application

- url: /.*
  script: coverfm.application