application: coverfm
version: 4
runtime: python
api_version: 1

handlers:
- url: /update
  script: coverfm.py
  login: admin

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /js
  static_dir: static/js
  
- url: /css
  static_dir: static/css
  
- url: /images
  static_dir: static/images

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /.*
  script: coverfm.py
